version: "3.9"

services:
  keycloak:
    image: jboss/keycloak:16.1.1
    restart: always
    ports:
      - "8081:8080"
    environment:
      DB_VENDOR: h2
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      KEYCLOAK_IMPORT: /tmp/local-realm.json
    volumes:
      - ${PWD}/keycloak:/tmp
