version: "3.9"

services:
  keycloak:
    image: jboss/keycloak:16.1.1
    restart: always
    ports:
      - 8081:8080
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      DB_VENDOR: h2
    volumes:
      - keycloak:/tmp

volumes:
  keycloak:
    driver: local
